// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vagabond.Api.Data;

#nullable disable

namespace Vagabond.Api.Migrations
{
    [DbContext(typeof(VagabondDbContext))]
    [Migration("20260404043529_AddRatingConstraint")]
    partial class AddRatingConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Vagabond.Api.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVisited")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3);

                    b.HasKey("Id");

                    b.ToTable("Destinations", t =>
                        {
                            t.HasCheckConstraint("CK_Destinations_Rating", "Rating >= 1 AND Rating <= 5");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
