<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MvcMovie/**/*.cs" />
    <Content Remove="MvcMovie/**" />
    <EmbeddedResource Remove="MvcMovie/**" />
    <None Remove="MvcMovie/**" />
  </ItemGroup>

</Project>
