// <auto-generated />
using System;
using InsureTrust.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsureTrust.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsureTrust.API.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentsSubmitted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaturityAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserPolicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.HasIndex("UserPolicyId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsureTrust.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedFeature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InsureTrust.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserPolicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentNumber")
                        .IsUnique();

                    b.HasIndex("UserPolicyId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InsureTrust.API.Models.PolicyRequiredField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("PolicyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTypeId");

                    b.ToTable("PolicyRequiredFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldName = "Nominee Name",
                            FieldType = "text",
                            IsMandatory = true,
                            PolicyTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            FieldName = "Nominee Relation",
                            FieldType = "text",
                            IsMandatory = true,
                            PolicyTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            FieldName = "Date of Birth",
                            FieldType = "date",
                            IsMandatory = true,
                            PolicyTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            FieldName = "Date of Birth",
                            FieldType = "date",
                            IsMandatory = true,
                            PolicyTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            FieldName = "Existing Medical Conditions",
                            FieldType = "text",
                            IsMandatory = false,
                            PolicyTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            FieldName = "Vehicle Registration Number",
                            FieldType = "text",
                            IsMandatory = true,
                            PolicyTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            FieldName = "Vehicle Make & Model",
                            FieldType = "text",
                            IsMandatory = true,
                            PolicyTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            FieldName = "Property Address",
                            FieldType = "text",
                            IsMandatory = true,
                            PolicyTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            FieldName = "Property Value (₹)",
                            FieldType = "text",
                            IsMandatory = true,
                            PolicyTypeId = 4
                        });
                });

            modelBuilder.Entity("InsureTrust.API.Models.PolicyTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PolicyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TermText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTypeId");

                    b.ToTable("PolicyTerms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PolicyTypeId = 1,
                            TermText = "Policy is valid for the tenure period specified at purchase."
                        },
                        new
                        {
                            Id = 2,
                            PolicyTypeId = 1,
                            TermText = "Premium must be paid monthly without grace period exceeding 30 days."
                        },
                        new
                        {
                            Id = 3,
                            PolicyTypeId = 1,
                            TermText = "Death claims require submission within 90 days of the event."
                        },
                        new
                        {
                            Id = 4,
                            PolicyTypeId = 2,
                            TermText = "Pre-existing diseases are covered after a 2-year waiting period."
                        },
                        new
                        {
                            Id = 5,
                            PolicyTypeId = 2,
                            TermText = "Cashless treatment available at 5000+ network hospitals."
                        },
                        new
                        {
                            Id = 6,
                            PolicyTypeId = 3,
                            TermText = "Vehicle must be registered in India and in roadworthy condition."
                        },
                        new
                        {
                            Id = 7,
                            PolicyTypeId = 3,
                            TermText = "Claims must be filed within 7 days of the incident."
                        });
                });

            modelBuilder.Entity("InsureTrust.API.Models.PolicyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseMonthlyPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxTenureMonths")
                        .HasColumnType("int");

                    b.Property<int>("MinTenureMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PolicyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseMonthlyPremium = 5000m,
                            Category = "Personal",
                            CoverageDetails = "Death benefit, Terminal illness rider, Accidental death benefit",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive life coverage protecting your family's financial future.",
                            Icon = "shield",
                            IsActive = true,
                            MaxTenureMonths = 360,
                            MinTenureMonths = 12,
                            Name = "Term Life"
                        },
                        new
                        {
                            Id = 2,
                            BaseMonthlyPremium = 3000m,
                            Category = "Personal",
                            CoverageDetails = "Hospitalization, Day care procedures, Pre & post hospitalization",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete medical coverage for hospitalization, surgeries, and outpatient care.",
                            Icon = "heart",
                            IsActive = true,
                            MaxTenureMonths = 60,
                            MinTenureMonths = 12,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            BaseMonthlyPremium = 2000m,
                            Category = "Personal",
                            CoverageDetails = "Own damage, Third party liability, Personal accident cover",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full coverage for cars and bikes against accidents, theft, and damage.",
                            Icon = "car",
                            IsActive = true,
                            MaxTenureMonths = 36,
                            MinTenureMonths = 12,
                            Name = "Vehicle"
                        },
                        new
                        {
                            Id = 4,
                            BaseMonthlyPremium = 1500m,
                            Category = "Personal",
                            CoverageDetails = "Structure damage, Contents, Liability protection",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protect your home and belongings against fire, flood, and burglary.",
                            Icon = "home",
                            IsActive = true,
                            MaxTenureMonths = 120,
                            MinTenureMonths = 12,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 5,
                            BaseMonthlyPremium = 8000m,
                            Category = "Business",
                            CoverageDetails = "Building damage, Business interruption, Liability",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Commercial property insurance for businesses and investment properties.",
                            Icon = "building",
                            IsActive = true,
                            MaxTenureMonths = 120,
                            MinTenureMonths = 12,
                            Name = "Property"
                        },
                        new
                        {
                            Id = 6,
                            BaseMonthlyPremium = 15000m,
                            Category = "Business",
                            CoverageDetails = "Group health, Group life, Disability coverage",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Group insurance plans covering all employees under a single policy.",
                            Icon = "users",
                            IsActive = true,
                            MaxTenureMonths = 60,
                            MinTenureMonths = 12,
                            Name = "Employee Group Benefits"
                        },
                        new
                        {
                            Id = 7,
                            BaseMonthlyPremium = 12000m,
                            Category = "Business",
                            CoverageDetails = "Equipment breakdown, Contractors risk, Erection all risks",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Specialized coverage for construction projects, equipment, and machinery.",
                            Icon = "settings",
                            IsActive = true,
                            MaxTenureMonths = 60,
                            MinTenureMonths = 12,
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("InsureTrust.API.Models.SupportQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("SupportQueries");
                });

            modelBuilder.Entity("InsureTrust.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KycDocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@insuretrust.com",
                            KycDocumentPath = "",
                            KycStatus = "Verified",
                            Name = "System Admin",
                            PanCard = "ADMIN1234A",
                            PasswordHash = "$2a$11$4X5LLa2RkUKBlzu./VhVFecpVV4yhVw6/5pHzzcMmvJetO68wCozq",
                            PhoneNo = "9999999999",
                            Role = "Admin",
                            UserNumber = "ADMIN001"
                        });
                });

            modelBuilder.Entity("InsureTrust.API.Models.UserPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DynamicFieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PackageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PolicyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("PolicyTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPolicies");
                });

            modelBuilder.Entity("InsureTrust.API.Models.Claim", b =>
                {
                    b.HasOne("InsureTrust.API.Models.UserPolicy", "UserPolicy")
                        .WithMany("Claims")
                        .HasForeignKey("UserPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPolicy");
                });

            modelBuilder.Entity("InsureTrust.API.Models.Notification", b =>
                {
                    b.HasOne("InsureTrust.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsureTrust.API.Models.Payment", b =>
                {
                    b.HasOne("InsureTrust.API.Models.UserPolicy", "UserPolicy")
                        .WithMany("Payments")
                        .HasForeignKey("UserPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPolicy");
                });

            modelBuilder.Entity("InsureTrust.API.Models.PolicyRequiredField", b =>
                {
                    b.HasOne("InsureTrust.API.Models.PolicyType", "PolicyType")
                        .WithMany("RequiredFields")
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyType");
                });

            modelBuilder.Entity("InsureTrust.API.Models.PolicyTerm", b =>
                {
                    b.HasOne("InsureTrust.API.Models.PolicyType", "PolicyType")
                        .WithMany("PolicyTerms")
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyType");
                });

            modelBuilder.Entity("InsureTrust.API.Models.SupportQuery", b =>
                {
                    b.HasOne("InsureTrust.API.Models.User", "User")
                        .WithMany("SupportQueries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsureTrust.API.Models.UserPolicy", b =>
                {
                    b.HasOne("InsureTrust.API.Models.PolicyType", "PolicyType")
                        .WithMany("UserPolicies")
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsureTrust.API.Models.User", "User")
                        .WithMany("UserPolicies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsureTrust.API.Models.PolicyType", b =>
                {
                    b.Navigation("PolicyTerms");

                    b.Navigation("RequiredFields");

                    b.Navigation("UserPolicies");
                });

            modelBuilder.Entity("InsureTrust.API.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("SupportQueries");

                    b.Navigation("UserPolicies");
                });

            modelBuilder.Entity("InsureTrust.API.Models.UserPolicy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
